name: Copy Files to Linux VM

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p $HOME/.ssh
        echo "${{ vars.SSH_KEY_NORMAL }}" > $HOME/.ssh/id_rsa
        chmod 600 $HOME/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.VM_IP }} >> $HOME/.ssh/known_hosts

    - name: Copy Files to Linux VM
      run: |
        # Variables
        USERNAME="${{ secrets.USERNAME }}"
        LINUX_VM_IP="${{ vars.VM_IP }}"
        LOCAL_FILE_PATH="C:/Users/admin/Documents/index.html"
        REMOTE_DIRECTORY="/home/ubuntu"
        
        LOCAL_FILE_PATH=$(wsl wslpath -a "$LOCAL_FILE_PATH")

        # Copy file using scp
        scp -i $HOME/.ssh/id_rsa "$LOCAL_FILE_PATH" "$USERNAME"@"$LINUX_VM_IP":"$REMOTE_DIRECTORY"
